# Pip installs

In [1]:
#pip install pandas
#pip install scikit-learn
#pip install tqdm
#pip install nltk
#pip install PyPDF2
#pip install spacy
#pip install torch
#pip install transformers
#pip install nbformat

SyntaxError: invalid syntax (308230526.py, line 1)

# Imports

In [5]:
import os
import pandas as pd
from itertools import combinations
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
from nltk.tokenize import sent_tokenize
import PyPDF2
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import unicodedata
import re
from sklearn.feature_extraction.text import CountVectorizer
import spacy
from collections import Counter
from transformers import BertForSequenceClassification, BertTokenizer
import torch

ModuleNotFoundError: No module named 'torch'

### One-time downloads

In [3]:
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('vader_lexicon')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
spacy.cli.download('nl_core_news_lg')
spacy.cli.download('en_core_web_lg')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\daanv\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!

✔ Download and installation successful
You can now load the package via spacy.load('nl_core_news_lg')
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

### Dutch or English

In [4]:
# Load Spacy and stop words Dutch
nlp = spacy.load('nl_core_news_lg')
stop_words = set(stopwords.words('dutch'))

# Load Spacy and stop words English
# nlp = spacy.load('en_core_web_lg')
# english_stop_words = set(stopwords.words('english'))

# Read PDF

In [5]:
def read_pdf(pdf_file, priority, exclude_pages=[1,2,3,4,5,22,23,24,25,26,27,87], filter_amount=20): # Adjust if needed
    if exclude_pages is None:
        exclude_pages = []

    # Adjust for 0-based indexing
    exclude_pages = [page - 1 for page in exclude_pages]

    all_text = ""
    page_numbers = []

    try:
        with open(pdf_file, "rb") as file:
            pdf_reader = PyPDF2.PdfReader(file)
            num_pages = len(pdf_reader.pages)

            # Iterate through pages except the last 'filter_amount' pages
            for page_num in range(num_pages - filter_amount):
                # Skip pages in the exclude_pages list
                if page_num in exclude_pages:
                    print(f"Skipping excluded page {page_num + 1} of {pdf_file}.")
                    continue

                page = pdf_reader.pages[page_num]
                page_text = page.extract_text()

                # Character check
                if len(page_text) < 60: # Adjust if needed
                    print(f"Skipping page {page_num + 1} of {pdf_file} with {len(page_text)} characters.")
                    continue

                all_text += page_text

                # Extract page number for each sentence on this page
                sentences = sent_tokenize(page_text)
                num_sentences = len(sentences)

                for _ in range(num_sentences):
                    page_numbers.append(page_num + 1)

            # Split text into sentences
            sentences = sent_tokenize(all_text)
            # Add sentences and their corresponding page numbers to DataFrame
            df_data = {'Phrase': sentences, 'Page': page_numbers[:len(sentences)], 'Priority': [priority]*len(sentences)}
            df = pd.DataFrame(df_data)
            return df

    except Exception as e:
        print(f"Error reading {pdf_file}: {e}")
        return pd.DataFrame()

# Text Preprocessing

In [6]:
def restore_split_words(sentence, nlp, stopwords):
    doc = nlp(sentence)
    new_tokens = []
    skip_next = False
    restored_words = []  # List to keep track of restored words for debugging

    for i, token in enumerate(doc[:-1]):  # Loop through tokens except for the last one
        if skip_next:
            skip_next = False
            continue
        next_token = doc[i + 1]
        # Check if either token is a stopword or a single character
        if (token.text.lower() in stopwords or next_token.text.lower() in stopwords or
            len(token.text) == 1 or len(next_token.text) == 1):
            new_tokens.append(token.text)  # Append first token only, skip combining
        else:
            combined_text = token.text + next_token.text
            if nlp.vocab[combined_text].is_oov:  # Check if the combined text is out-of-vocabulary
                new_tokens.append(token.text)
            else:
                new_tokens.append(combined_text)
                restored_words.append((token.text, next_token.text, combined_text))  # Add the original and restored word to the list
                skip_next = True  # Skip the next token since it has been combined with the current one
    if not skip_next and doc:  # Append the last token if it wasn't combined
        new_tokens.append(doc[-1].text)

    sentence_after = ' '.join(new_tokens)  # Reconstruct sentence from new tokens

    if restored_words:  # Print restoration changes if any
        print("Restoration changes:")
        for original1, original2, combined in restored_words:
            print(f"{original1} + {original2} -> {combined}")
            
    return sentence_after

def process_text(df):
    processed_data = {'Phrase': [], 'Page': [], 'Priority': []}
    for _, row in df.iterrows():
        sentence = row['Phrase']

        sentence = unicodedata.normalize('NFKD', sentence)
        sentence = ''.join([c for c in sentence if not unicodedata.combining(c)])
        sentence = sentence.replace('\n', '').lower()
        sentence = re.sub(r'[^a-zA-Z\s]', '', sentence)
        sentence = sentence.replace("rightarrow", "").replace("leftarrow", "")

        # Restore potentially split words before removing stopwords
        restored_sentence = restore_split_words(sentence, nlp, stop_words)

        # Named entity recognition (NER) to filter out personal names
        doc = nlp(restored_sentence)  # Rebuild sentence for NER
        filtered_names = [ent.text for ent in doc.ents if ent.label_ == 'PERSON']
        if filtered_names:
            print("Filtered out personal names:", filtered_names)
        for name in filtered_names:
            restored_sentence = restored_sentence.replace(name, '')

        words = word_tokenize(restored_sentence)
        processed_words = [w for w in words if w.lower() not in stop_words and len(w) < 30 and len(w) > 1]

        processed_data['Phrase'].append(processed_words)  # Store processed words as a list
        processed_data['Page'].append(row['Page'])
        processed_data['Priority'].append(row['Priority'])

    processed_df = pd.DataFrame(processed_data)
    return processed_df

# Word Pair Generating

In [7]:
def generate_word_pairs(df):
    # Define the inner function to generate word pairs for each phrase
    def generate_pairs(tokens):
        pairs = list(combinations(tokens, 2))  # Generate all possible combinations of word pairs
        return [(word1, word2) for word1, word2 in pairs if word1 != word2]

    # Apply the generate_pairs function to each phrase to generate word pairs
    df['word_pairs'] = df['Phrase'].apply(generate_pairs)

    # Flatten the list of word pairs
    flat_pairs = [pair for sublist in df['word_pairs'] for pair in sublist]

    # Count occurrences of each word pair
    word_pair_counts = Counter(flat_pairs)

    # Create a DataFrame to store word pairs and their counts
    word_pair_df = pd.DataFrame(word_pair_counts.items(), columns=['Word Pair', 'Count'])
    word_pair_df['Word1'] = word_pair_df['Word Pair'].apply(lambda x: x[0])
    word_pair_df['Word2'] = word_pair_df['Word Pair'].apply(lambda x: x[1])

    # Concatenate Word1 and Word2 columns to create a new column for sorting and eliminate duplicates
    word_pair_df['Sorted Pair'] = word_pair_df.apply(lambda x: tuple(sorted([x['Word1'], x['Word2']])), axis=1)
    word_pair_df = word_pair_df.drop_duplicates(subset='Sorted Pair').drop(columns='Sorted Pair')

    return word_pair_df[['Word Pair', 'Word1', 'Word2', 'Count']]

# Predict Category

In [8]:
def predict_category(word_df, Label, batch_size=256):
    label_mapping = {
        0: 'Water',
        1: 'Mobiliteit',
        2: 'Duurzaamheid',
        3: 'Overige'
    }

    # Setup GPU/CPU
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f'Using device: {device}')

    # Load model and tokenizer
    tokenizer = BertTokenizer.from_pretrained("wietsedv/bert-base-dutch-cased")
    model = BertForSequenceClassification.from_pretrained('model_6_bertje_df_all')
    model.to(device)  # Move model to GPU

    word1_predictions = []
    word2_predictions = []

    num_batches = (len(word_df) + batch_size - 1) // batch_size

    for i in range(0, len(word_df), batch_size):
        batch_df = word_df.iloc[i:i+batch_size]

        tokens_word1 = tokenizer(batch_df['Word1'].tolist(), padding=True, truncation=True, return_tensors='pt').to(device)
        tokens_word2 = tokenizer(batch_df['Word2'].tolist(), padding=True, truncation=True, return_tensors='pt').to(device)

        with torch.no_grad():
            outputs_word1 = model(**tokens_word1)
            outputs_word2 = model(**tokens_word2)

        probabilities_word1 = torch.softmax(outputs_word1.logits, dim=1)
        probabilities_word2 = torch.softmax(outputs_word2.logits, dim=1)

        for j in range(len(batch_df)):
            predicted_label_index_word1 = torch.argmax(probabilities_word1[j], dim=0).item()
            predicted_label_word1 = label_mapping[predicted_label_index_word1]
            word1_predictions.append(predicted_label_word1)

            predicted_label_index_word2 = torch.argmax(probabilities_word2[j], dim=0).item()
            predicted_label_word2 = label_mapping[predicted_label_index_word2]
            word2_predictions.append(predicted_label_word2)

        # Print progress
        progress = (i // batch_size) + 1
        print(f'Processed batch {progress}/{num_batches}')

    result_df = pd.DataFrame({
        'Word_Pair': word_df['Word Pair'],
        'Word1': word_df['Word1'],
        'Word1_Category': word1_predictions,
        'Word2': word_df['Word2'],
        'Word2_Category': word2_predictions,
        'Count': word_df['Count']
    })

    # Filter rows where either Word1 or Word2 matches the specified label
    result_df = result_df[(result_df['Word1_Category'] == Label) | (result_df['Word2_Category'] == Label)]

    return result_df

# Top Word Selection with TF-IDF

In [9]:
class PriorityTfidfVectorizer(TfidfVectorizer):
    def __init__(self, priorities=None, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=float, norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False):
        super().__init__(input=input, encoding=encoding, decode_error=decode_error, strip_accents=strip_accents, lowercase=lowercase, preprocessor=preprocessor, tokenizer=tokenizer, stop_words=stop_words, token_pattern=token_pattern, ngram_range=ngram_range, analyzer=analyzer, max_df=max_df, min_df=min_df, max_features=max_features, vocabulary=vocabulary, binary=binary, dtype=dtype, norm=norm, use_idf=use_idf, smooth_idf=smooth_idf, sublinear_tf=sublinear_tf)
        self.priorities = priorities

    def fit_transform(self, raw_documents, y=None):
        tfidf_matrix = super().fit_transform(raw_documents, y)
        # Multiply tf-idf scores by the priority of the document
        for i, priority in enumerate(self.priorities):
            tfidf_matrix[i, :] *= priority
        return tfidf_matrix

# Create TF-IDF vectors
def create_tfidf_vectors(documents, priorities):
    vectorizer = PriorityTfidfVectorizer(priorities=priorities)
    tfidf_matrix = vectorizer.fit_transform(documents)
    feature_names = vectorizer.get_feature_names_out()
    return tfidf_matrix, feature_names

def select_top_words_by_tfidf(processed_df, top_n=300):
    # Join the phrases by page number into single strings
    grouped_text = processed_df.groupby('Page')['Phrase'].apply(lambda x: ' '.join(map(str, x))).tolist()
    priorities = processed_df['Priority'].unique()
    
    # Calculate the TF-IDF matrix with priorities
    tfidf_matrix, feature_names = create_tfidf_vectors(grouped_text, priorities)
    
    # Create a DataFrame with the scores per page
    weightdf = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)
    weightdf = weightdf.T  # Transpose to have words as rows
    weightdf['TF-IDF_max'] = weightdf.max(axis=1)
    
    # Sort the DataFrame by TF-IDF_max in descending order
    sorted_weightdf = weightdf.sort_values(by='TF-IDF_max', ascending=False)
    
    # Select the top N words
    top_words = sorted_weightdf.head(top_n).index.tolist()
    return top_words

# Top Word Selection with TF-IDF with Filter for categorisation

In [10]:
def select_top_words_by_tfidf_cat(processed_df, word_df, top_n=300): # Adjust top_n if needed
    # Join the phrases by page number into single strings
    grouped_text = processed_df.groupby('Page')['Phrase'].apply(lambda x: ' '.join(map(str, x))).tolist()
    priorities = processed_df['Priority'].unique()
    
    # Calculate the TF-IDF matrix with priorities
    tfidf_matrix, feature_names = create_tfidf_vectors(grouped_text, priorities)
    
    # Create a DataFrame with the scores per page
    weightdf = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)
    weightdf = weightdf.T  # Transpose to have words as rows
    weightdf['TF-IDF_max'] = weightdf.max(axis=1)
    
    # Sort the DataFrame by TF-IDF_max in descending order
    sorted_weightdf = weightdf.sort_values(by='TF-IDF_max', ascending=False)
    
    top_words_filtered = sorted_weightdf[sorted_weightdf.index.isin(word_df['Word1']) | sorted_weightdf.index.isin(word_df['Word2'])]
    # Select the top N words
    top_words = top_words_filtered.head(top_n).index.tolist()
    return top_words

# Social Graph Constructing

In [11]:
def create_social_graph_from_top_words(word_df, top_words, processed_df):
    social_graph_df = word_df[(word_df['Word1'].isin(top_words)) & (word_df['Word2'].isin(top_words))].sort_values('Word1')

    # Calculate occurrence count for each word, considering priorities
    list_of_words = list(set(list(social_graph_df['Word1'].unique()) + list(social_graph_df['Word2'].unique())))
    occurrence_df = pd.DataFrame({'Word': list_of_words, 'Occurrence': [
        sum(word in tokens for tokens, priority in zip(processed_df['Phrase'], processed_df['Priority']) for _ in range(int(priority))) for word in list_of_words
    ]})
    # Merge occurrences back into the social graph DataFrame
    social_graph_df = pd.merge(social_graph_df, occurrence_df, left_on='Word1', right_on='Word', how='left').rename(columns={'Occurrence': 'Word1_occurrence'}).drop('Word', axis=1)
    social_graph_df = pd.merge(social_graph_df, occurrence_df, left_on='Word2', right_on='Word', how='left').rename(columns={'Occurrence': 'Word2_occurrence'}).drop('Word', axis=1)
    
    # Calculate weighted count using the PMI formula 
    social_graph_df['Count_weighted'] = social_graph_df['Count'] / (social_graph_df['Word1_occurrence'] * social_graph_df['Word2_occurrence'])
    
    return social_graph_df

# Main function

In [12]:
def main(pdf_files, doc_weights):
    df_data = {'Phrase': [], 'Page': [], 'Priority': []}  # Initialize df_data dictionary
    for pdf_file in pdf_files:
        if os.path.exists(pdf_file):
            text_df = read_pdf(pdf_file, doc_weights[pdf_file])
            if text_df is not None:  # Check if read_pdf returned a valid DataFrame
                df_data['Phrase'].extend(text_df['Phrase'])
                df_data['Page'].extend(text_df['Page'])
                df_data['Priority'].extend(text_df['Priority'])
            else:
                print(f"Error reading text from {pdf_file}")
        else:
            print(f"File '{pdf_file}' does not exist.")
    
    df = pd.DataFrame(df_data)  # Create DataFrame from df_data
    processed_df = process_text(df)  # Process the text DataFrame
    word_df = generate_word_pairs(processed_df)  # Generate word pairs df on processed data
    
    # Select the top 300 words based on TF-IDF scores
    top_n_words = select_top_words_by_tfidf(processed_df)
    
    # Create the social graph from the top 300 words
    social_graph_df = create_social_graph_from_top_words(word_df, top_n_words, processed_df)
    
    return social_graph_df, processed_df

# Main function with categorisation

In [13]:
def main_cat(pdf_files, doc_weights, Label):
    df_data = {'Phrase': [], 'Page': [], 'Priority': []}  # Initialize df_data dictionary
    for pdf_file in pdf_files:
        if os.path.exists(pdf_file):
            text_df = read_pdf(pdf_file, doc_weights[pdf_file])
            if text_df is not None:  # Check if read_pdf returned a valid DataFrame
                df_data['Phrase'].extend(text_df['Phrase'])
                df_data['Page'].extend(text_df['Page'])
                df_data['Priority'].extend(text_df['Priority'])
            else:
                print(f"Error reading text from {pdf_file}")
        else:
            print(f"File '{pdf_file}' does not exist.")
    

    df = pd.DataFrame(df_data)  # Create DataFrame from df_data
    processed_df = process_text(df)  # Process the text DataFrame
    word_df = generate_word_pairs(processed_df)  # Generate word pairs df on processed data
        

    # Choices are 'Water', 'Mobiliteit', 'Duurzaamheid', 'Armoede', 'Overige'
    word_df_cat = predict_category(word_df, Label)
    
    # Select the top 300 words based on TF-IDF scores
    top_n_words = select_top_words_by_tfidf_cat(processed_df, word_df_cat)

    
    social_graph = create_social_graph_from_top_words(word_df_cat, top_n_words, processed_df)

    return social_graph, processed_df

In [14]:
# List of PDF files to process
#pdf_files = ["presentatie_gebiedsvisie.pdf", "Ontwikkeldocument+NPLG_PDF.pdf"]
pdf_files = ["INEK.pdf"]
#pdf_files = [r"C:\Users\rosal\DataspellProjects\VanWonen\Notebooks\Kennisgrafiek\1.pdf"]



#rosalie
#pdf_files = [r"C:\Users\rosal\DataspellProjects\VanWonen\Notebooks\Kennisgrafiek\1.pdf",r"C:\Users\rosal\DataspellProjects\VanWonen\Notebooks\Werk\Final_models\Ontwikkeldocument+NPLG_PDF.pdf"]
# pdf_files = ["Armoede- en Schuldenmonitor_2023_DEF 27-9.pdf"]

In [15]:
# Define the document weights
doc_weights = {"INEK.pdf": 1.0}

#doc_weights = {r"C:\Users\rosal\DataspellProjects\VanWonen\Notebooks\Kennisgrafiek\1.pdf": 1.0}


#rosalie
#doc_weights = {r"C:\Users\rosal\DataspellProjects\VanWonen\Notebooks\Kennisgrafiek\1.pdf": 1.0, r"C:\Users\rosal\DataspellProjects\VanWonen\Notebooks\Werk\Final_models\Ontwikkeldocument+NPLG_PDF.pdf" : 1.0}

# doc_weights = {"Armoede- en Schuldenmonitor_2023_DEF 27-9.pdf": 1.0}

300 characters seems to be the 'golden number' in this case, this was determined through trial and error. When inspecting the document and checking the removed pages, setting the threshold at 300 removes every unwanted page while leaving every important page intact.

In [16]:
# Call the main function
# relations_df, df_data = main(pdf_files, doc_weights)

# Call the main function with category
relations_df, df_data = main_cat(pdf_files,doc_weights, 'Duurzaamheid')

Skipping excluded page 1 of INEK.pdf.
Skipping excluded page 2 of INEK.pdf.
Skipping excluded page 3 of INEK.pdf.
Skipping excluded page 4 of INEK.pdf.
Skipping excluded page 5 of INEK.pdf.
Skipping excluded page 22 of INEK.pdf.
Skipping excluded page 23 of INEK.pdf.
Skipping excluded page 24 of INEK.pdf.
Skipping excluded page 25 of INEK.pdf.
Skipping excluded page 26 of INEK.pdf.
Skipping excluded page 27 of INEK.pdf.
Skipping page 86 of INEK.pdf with 58 characters.
Skipping excluded page 87 of INEK.pdf.
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
vijf + jaar -> vijfjaar
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
tussen + partijen -> tussenpartijen
Restoration changes:
ten + minste -> tenminste
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
be + eindigd -> beeindigd
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
sector + overstijgende -> sectoroverstijgende
Restoration changes:
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
Restoration changes:
ten + minste -> tenminste
energie + verbruik -> energieverbruik
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ieder + geval -> iedergeval
Restoration changes:
hoge + druk -> hogedruk
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['world competitiveness']
Restoration changes:
vrij + komt -> vrijkomt
Restoration changes:
ten + minste -> tenminste
ten + opzichte -> tenopzichte
Restoration changes:
gelijk + gesteld -> gelijkgesteld
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['energietransitieondanks']
Restoration changes:
klimaat + beleid -> klimaatbeleid
Filtered out personal names: ['ontwerpnovi']
Restoration changes:
langeter + mijndoelstellingen -> langetermijndoelstellingen
Filtered out personal names: ['kabinetsaanpak']
Restoration changes:
vijf + jaar -> vijfjaar
Restoration changes:
korte + termijn -> kortetermijn
Filtered out personal names: ['klimaatnota']
Restoration changes:
tussen + partijen -> tussenpartijen
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + minste -> tenminste
Filtered out personal names: ['tse']
Filtered out personal names: ['tse']
Filtered out personal names: ['tse']
Filtered out personal names: ['ontwerpnovi']
Filtered out personal names: ['ontwerpnovi']
Filtered out personal names: ['ontwerpnovi', 'energiestrategieen']
Filtered out personal names: ['energieinfrastructuur', 'ontwerpnovi']
Filtered out personal names: ['energiestrategieen']
Restoration changes:
water + robuust -> waterrobuust
Filtered out personal names: ['energiestrategieen']
Filtered out personal names: ['oktober   ']
Filtered out personal names: ['klimaatnota']
Filtered out personal names: ['klimaatnota']
Restoration changes:
mee + konden -> meekonden
Filtered out personal names: ['publieksaanpak']
Restoration changes:
water + rekening -> waterrekening
Restoration changes:
eerder + genoemde -> eerdergenoemde
Restoration changes:
ten + gevolge -> tengevolge
Filtered out personal names: ['publieksaanpak']
Filtered out personal names: ['publieksaanpak']
Restoration changes:
open + staat -> openstaat
Filtered out personal names: ['lidstatenhet']
Restoration changes:
bel + den -> belden
Restoration changes:
online + platform -> onlineplatform
Restoration changes:
samen + gaan -> samengaan
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['lulucf boekhoudcategorieen']
Restoration changes:
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
Filtered out personal names: ['ndcs']
Filtered out personal names: ['bronneni']
Restoration changes:
openbaar + vervoer -> openbaarvervoer
Restoration changes:
goed + passende -> goedpassende
Restoration changes:
handelingsper + spectief -> handelingsperspectief
eigen + huis -> eigenhuis
Filtered out personal names: ['landgebruikeen duurzame']
Filtered out personal names: ['klimaatslim']
Restoration changes:
zoetwater + voorziening -> zoetwatervoorziening
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
financierings + mogelijkheden -> financieringsmogelijkheden
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + minste -> tenminste
Restoration changes:
ieder + geval -> iedergeval
Restoration changes:
vo + or -> voor
ten + minste -> tenminste
Filtered out personal names: ['energiestrategieen']
Filtered out personal names: ['landbouwin']
Restoration changes:
ieder + geval -> iedergeval
Filtered out personal names: ['iii']
Filtered out personal names: ['hernieuwbareenergietechnologieaanpak']
Restoration changes:
systeemin + tegratie -> systeemintegratie
Filtered out personal names: ['iii iv en v']
Restoration changes:
lange + termijn -> langetermijn
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + minste -> tenminste
Restoration changes:
ten + minste -> tenminste
ten + opzichte -> tenopzichte
Restoration changes:
gebruik + maken -> gebruikmaken
Restoration changes:
vastgoed + portefeuille -> vastgoedportefeuille
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
toe + geven -> toegeven
Restoration changes:
openbaar + vervoer -> openbaarvervoer
Restoration changes:
klimaat + neutrale -> klimaatneutrale
Filtered out personal names: ['groningen van   ']
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
transport + capaciteit -> transportcapaciteit
Restoration changes:
ten + slotte -> tenslotte
Restoration changes:
real + time -> realtime
Restoration changes:
ten + minste -> tenminste
Restoration changes:
an + sich -> ansich
Restoration changes:
waar + nodig -> waarnodig
Filtered out personal names: ['standaardplatforms']
Restoration changes:
gebruik + maakt -> gebruikmaakt
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
real + time -> realtime
Restoration changes:
real + time -> realtime
Restoration changes:
waar + nodig -> waarnodig
Restoration changes:
energie + levering -> energielevering
Restoration changes:
goed + werkende -> goedwerkende
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
lange + termijn -> langetermijn
Restoration changes:
groen + gas -> groengas
Restoration changes:
business + case -> businesscase
lange + termijn -> langetermijn
Restoration changes:
elektrici + teitsmarkt -> elektriciteitsmarkt
Filtered out personal names: ['medio   ']
Filtered out personal names: ['noodleverancier']
Restoration changes:
vroeg + signalering -> vroegsignalering
Restoration changes:
basis + vormen -> basisvormen
Filtered out personal names: ['sleuteltechnologieen']
Restoration changes:
korte + termijn -> kortetermijn
lange + termijn -> langetermijn
Filtered out personal names: ['innovatieprogrammas mmips']
Restoration changes:
achter + blijven -> achterblijven
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
vertegen + woordiging -> vertegenwoordiging
Restoration changes:
eerder + genoemd -> eerdergenoemd
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
Filtered out personal names: ['lulucfzoals']
Restoration changes:
gebruik + gemaakt -> gebruikgemaakt
Restoration changes:
energiebespa + ringsmaatregelen -> energiebesparingsmaatregelen
vijf + jaar -> vijfjaar
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + koste -> tenkoste
Restoration changes:
kabinet + ten -> kabinetten
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + minste -> tenminste
Filtered out personal names: ['financieringc']
Restoration changes:
subsidie + regeling -> subsidieregeling
Restoration changes:
heen + gaat -> heengaat
Restoration changes:
ten + minste -> tenminste
ieder + geval -> iedergeval
Restoration changes:
terug + geleverd -> teruggeleverd
Filtered out personal names: ['btw']
Restoration changes:
postcoder + oosregeling -> postcoderoosregeling
Restoration changes:
stap + per -> stapper
Restoration changes:
rekening + houdend -> rekeninghoudend
toepassings + mogelijkheden -> toepassingsmogelijkheden
Restoration changes:
concept + wetsvoorstel -> conceptwetsvoorstel
elektriciteits + productie -> elektriciteitsproductie
Filtered out personal names: ['minimumprijs']
Restoration changes:
eerder + genoemde -> eerdergenoemde
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
noord + nederland -> noordnederland
Filtered out personal names: ['rijnmondmoerdijk']
Restoration changes:
nadeelcom + pensatie -> nadeelcompensatie
Restoration changes:
benzine + auto -> benzineauto
Restoration changes:
benzine + auto -> benzineauto
Filtered out personal names: ['wbcsd']
Restoration changes:
kunststof + producten -> kunststofproducten
Filtered out personal names: ['niethernieuwbare']
Restoration changes:
gebruik + maken -> gebruikmaken
Restoration changes:
vijf + jaar -> vijfjaar
Restoration changes:
ter + beschikking -> terbeschikking
Restoration changes:
korte + termijn -> kortetermijn
eigen + huis -> eigenhuis
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
eigen + huis -> eigenhuis
Restoration changes:
energie + neutrale -> energieneutrale
Restoration changes:
eigen + woning -> eigenwoning
Restoration changes:
ten + minste -> tenminste
Restoration changes:
utiliteits + gebouwen -> utiliteitsgebouwen
Restoration changes:
groen + gas -> groengas
groen + gas -> groengas
Filtered out personal names: ['landgebruikin']
Restoration changes:
klimaat + actieplan -> klimaatactieplan
Restoration changes:
energie + prestatie -> energieprestatie
Filtered out personal names: ['i ii iii']
Filtered out personal names: ['elektriciteitgas']
Restoration changes:
elektrici + teitssysteem -> elektriciteitssysteem
an + sich -> ansich
Filtered out personal names: ['no   ']
Restoration changes:
gas + verbruik -> gasverbruik
Restoration changes:
leverings + zekerheid -> leveringszekerheid
Filtered out personal names: ['standaardplatforms']
Filtered out personal names: ['denemarken van   ', 'belgie van   ']
Filtered out personal names: ['wetgevingsagenda']
Restoration changes:
elektrici + teitssysteem -> elektriciteitssysteem
Restoration changes:
real + time -> realtime
Restoration changes:
real + time -> realtime
Restoration changes:
goed + werkend -> goedwerkend
Restoration changes:
elektrici + teitssysteem -> elektriciteitssysteem
Restoration changes:
elektrici + teitsmarkt -> elektriciteitsmarkt
Restoration changes:
real + time -> realtime
Filtered out personal names: ['for the dutch']
Filtered out personal names: ['medio   ']
Filtered out personal names: ['noodleverancier']
Restoration changes:
real + time -> realtime
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
publiek + private -> publiekprivate
Restoration changes:
innovatie + gericht -> innovatiegericht
Filtered out personal names: ['sleuteltechnologieen']
Restoration changes:
high + tech -> hightech
Filtered out personal names: ['innovatieprogrammas mmips']
Restoration changes:
ten + minste -> tenminste
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
transport + brandstoffen -> transportbrandstoffen
Restoration changes:
productie + processen -> productieprocessen
Filtered out personal names: ['mmips']
Filtered out personal names: ['mmips']
Filtered out personal names: ['mmips']
Filtered out personal names: ['mmips']
Restoration changes:
sociaal + economische -> sociaaleconomische
Restoration changes:
mee + krijgen -> meekrijgen
Restoration changes:
vijf + jaar -> vijfjaar
Restoration changes:
werkgele + genheidseffecten -> werkgelegenheidseffecten
Filtered out personal names: ['vertaaldvoor']
Filtered out personal names: ['mmips']
Filtered out personal names: ['ocean energy']
Filtered out personal names: ['mmips', 'innovatieprogrammas mmipssetplan', 'eranetmission']
Restoration changes:
elektriciteits + opwekking -> elektriciteitsopwekking
consu + mers -> consumers
Filtered out personal names: ['solarpv', 'solar cofundconverting']
Filtered out personal names: ['eranet']
Restoration changes:
energiesy + steem -> energiesysteem
Filtered out personal names: ['steemindustrial energy']
Filtered out personal names: ['eranet', 'cofundelectromobility   eranetsustainable biofuels bioenergy']
Filtered out personal names: ['eranet cofund electromobility   ']
Restoration changes:
maat + schappelijk -> maatschappelijk
Filtered out personal names: ['ccus']
Filtered out personal names: ['ccus']
Filtered out personal names: ['ocean energy']
Restoration changes:
samenwerkings + verbanden -> samenwerkingsverbanden
Filtered out personal names: ['eranet cofund']
Filtered out personal names: ['eranet']
Filtered out personal names: ['eranet']
Filtered out personal names: ['eranet']
Filtered out personal names: ['spendingmi thirdyear']
Filtered out personal names: ['jan   to']
Filtered out personal names: ['enduse']
Filtered out personal names: ['dvii']
Filtered out personal names: ['wva']
Filtered out personal names: ['cofinanciert']
Filtered out personal names: ['cofinanciert']
Filtered out personal names: ['mmips']
Filtered out personal names: ['mmips']
Restoration changes:
lange + termijn -> langetermijn
Restoration changes:
gebruik + gemaakt -> gebruikgemaakt
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
broeikasga + semissies -> broeikasgasemissies
Restoration changes:
scenario + studie -> scenariostudie
Restoration changes:
vastge + steld -> vastgesteld
Restoration changes:
energie + verbruiken -> energieverbruiken
Restoration changes:
decennia + lang -> decennialang
Filtered out personal names: ['huishoudensgrootte       economische activiteit hersteld van de crisisin']
Restoration changes:
drie + kwart -> driekwart
Restoration changes:
efficiency + verbeteringen -> efficiencyverbeteringen
Restoration changes:
verder + af -> verderaf
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
ten + gevolge -> tengevolge
Restoration changes:
stand + komen -> standkomen
Restoration changes:
snelst + groeiende -> snelstgroeiende
Filtered out personal names: ['china mozambique']
Restoration changes:
lange + termijn -> langetermijn
Restoration changes:
korte + termijn -> kortetermijn
Filtered out personal names: ['dunningshout']
Restoration changes:
korte + termijn -> kortetermijn
lange + termijn -> langetermijn
Restoration changes:
lange + termijn -> langetermijn
Restoration changes:
gebruik + gemaakt -> gebruikgemaakt
Restoration changes:
gebruik + gemaakt -> gebruikgemaakt
Filtered out personal names: ['future renewable energy costs']
Restoration changes:
korte + termijn -> kortetermijn
Filtered out personal names: ['ntwosubscriptomethaan']
Filtered out personal names: ['lulucf   ']
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + koste -> tenkoste
Filtered out personal names: ['lulucf']
Filtered out personal names: ['lulucf']
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
emissiehan + delssysteem -> emissiehandelssysteem
Filtered out personal names: ['emissiesin']
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
eerder + genoemde -> eerdergenoemde
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['twoliningzeroliningthreeliningzerolininghernieuwbare']
Restoration changes:
twee + derde -> tweederde
Restoration changes:
elektriciteit + sproductie -> elektriciteitsproductie
Restoration changes:
begin + jaren -> beginjaren
Restoration changes:
ten + koste -> tenkoste
Filtered out personal names: ['brandstofpetajouleafval']
Filtered out personal names: ['waterstoom']
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['procesgas']
Restoration changes:
meest + gebruikte -> meestgebruikte
Restoration changes:
gereed + komen -> gereedkomen
Restoration changes:
groei + plaats -> groeiplaats
Restoration changes:
energie + prestatie -> energieprestatie
Restoration changes:
gebouw + gebonden -> gebouwgebonden
Restoration changes:
vijf + jaar -> vijfjaar
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['pseudogroningengas']
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
elektriciteit + sproductie -> elektriciteitsproductie
verder + af -> verderaf
Restoration changes:
aardolie + producten -> aardolieproducten
Filtered out personal names: ['cova']
Restoration changes:
elek + triciteits -> elektriciteits
Filtered out personal names: ['vraagnietoperationeel']
Filtered out personal names: ['nluk']
Restoration changes:
leverings + zekerheid -> leveringszekerheid
Restoration changes:
uitbreiding + splannen -> uitbreidingsplannen
Restoration changes:
inter + ne -> interne
Restoration changes:
transfor + matorstation -> transformatorstation
Filtered out personal names: ['aardgasde transportnetten']
Restoration changes:
ex + tra -> extra
Restoration changes:
gas + transport -> gastransport
Restoration changes:
verschill + ende -> verschillende
Restoration changes:
waar + vanuit -> waarvanuit
Restoration changes:
weer + licht -> weerlicht
Restoration changes:
korte + termijn -> kortetermijn
Restoration changes:
gebruik + gemaakt -> gebruikgemaakt
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
relat + ief -> relatief
Restoration changes:
ver + enigd -> verenigd
Filtered out personal names: ['wweerrkkiinngg   eelleekkttrriicciitteeiitt   ']
Restoration changes:
gebruik + gemaakt -> gebruikgemaakt
Restoration changes:
consume + ntenbescherming -> consumentenbescherming
Filtered out personal names: ['eelleekkttrriicciitteeiitt   ']
Restoration changes:
ten + opzichte -> tenopzichte
Restoration changes:
li + quiditeit -> liquiditeit
Filtered out personal names: ['aardgasde nederlandse']
Restoration changes:
ten + opzichte -> tenopzichte
ten + opzichte -> tenopzichte
Filtered out personal names: ['dahl hirschmann']
Restoration changes:
ver + werking -> verwerking
Restoration changes:
ten + opzichte -> tenopzichte
Filtered out personal names: ['dahl hirschmann']
Restoration changes:
ver + werking -> verwerking
Restoration changes:
po + verty -> poverty
Restoration changes:
energiear + moede -> energiearmoede
Restoration changes:
betalingsachterst + and -> betalingsachterstand
Restoration changes:
ind + icator -> indicator
Restoration changes:
per + centage -> percentage
Restoration changes:
fi + guur -> figuur
Filtered out personal names: ['van huishoudenspblnlin   ']
Restoration changes:
netto + kosten -> nettokosten
Filtered out personal names: ['energielast']
Restoration changes:
technologie + sector -> technologiesector
Restoration changes:
clean + tech -> cleantech
Restoration changes:
clean + tech -> cleantech
clean + tech -> cleantech
Filtered out personal names: ['the countrys']
Filtered out personal names: ['commercialised']
Filtered out personal names: ['httpswwwcleantechcomdit']
Restoration changes:
energie + gerelateerde -> energiegerelateerde
Restoration changes:

C:\Users\naomi\anaconda3\Lib\site-packages\transformers\models\bert\modeling_bert.py:435: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

Processed batch 1/744
Processed batch 2/744
Processed batch 3/744
Processed batch 4/744
Processed batch 5/744
Processed batch 6/744
Processed batch 7/744
Processed batch 8/744
Processed batch 9/744
Processed batch 10/744
Processed batch 11/744
Processed batch 12/744
Processed batch 13/744
Processed batch 14/744
Processed batch 15/744
Processed batch 16/744
Processed batch 17/744
Processed batch 18/744
Processed batch 19/744
Processed batch 20/744
Processed batch 21/744
Processed batch 22/744
Processed batch 23/744
Processed batch 24/744
Processed batch 25/744
Processed batch 26/744
Processed batch 27/744
Processed batch 28/744
Processed batch 29/744
Processed batch 30/744
Processed batch 31/744
Processed batch 32/744
Processed batch 33/744
Processed batch 34/744
Processed batch 35/744
Processed batch 36/744
Processed batch 37/744
Processed batch 38/744
Processed batch 39/744
Processed batch 40/744
Processed batch 41/744
Processed batch 42/744
Processed batch 43/744
Processed batch 44/744
Processed batch 45/744
Processed batch 46/744
Processed batch 47/744
Processed batch 48/744
Processed batch 49/744
Processed batch 50/744
Processed batch 51/744
Processed batch 52/744
Processed batch 53/744
Processed batch 54/744
Processed batch 55/744
Processed batch 56/744
Processed batch 57/744
Processed batch 58/744
Processed batch 59/744
Processed batch 60/744
Processed batch 61/744
Processed batch 62/744
Processed batch 63/744
Processed batch 64/744
Processed batch 65/744
Processed batch 66/744
Processed batch 67/744
Processed batch 68/744
Processed batch 69/744
Processed batch 70/744
Processed batch 71/744
Processed batch 72/744
Processed batch 73/744
Processed batch 74/744
Processed batch 75/744
Processed batch 76/744
Processed batch 77/744
Processed batch 78/744
Processed batch 79/744
Processed batch 80/744
Processed batch 81/744
Processed batch 82/744
Processed batch 83/744
Processed batch 84/744
Processed batch 85/744
Processed batch 86/744
Processed batch 87/744
Processed batch 88/744
Processed batch 89/744
Processed batch 90/744
Processed batch 91/744
Processed batch 92/744
Processed batch 93/744
Processed batch 94/744
Processed batch 95/744
Processed batch 96/744
Processed batch 97/744
Processed batch 98/744
Processed batch 99/744
Processed batch 100/744
Processed batch 101/744
Processed batch 102/744
Processed batch 103/744
Processed batch 104/744
Processed batch 105/744
Processed batch 106/744
Processed batch 107/744
Processed batch 108/744
Processed batch 109/744
Processed batch 110/744
Processed batch 111/744
Processed batch 112/744
Processed batch 113/744
Processed batch 114/744
Processed batch 115/744
Processed batch 116/744
Processed batch 117/744
Processed batch 118/744
Processed batch 119/744
Processed batch 120/744
Processed batch 121/744
Processed batch 122/744
Processed batch 123/744
Processed batch 124/744
Processed batch 125/744
Processed batch 126/744
Processed batch 127/744
Processed batch 128/744
Processed batch 129/744
Processed batch 130/744
Processed batch 131/744
Processed batch 132/744
Processed batch 133/744
Processed batch 134/744
Processed batch 135/744
Processed batch 136/744
Processed batch 137/744
Processed batch 138/744
Processed batch 139/744
Processed batch 140/744
Processed batch 141/744
Processed batch 142/744
Processed batch 143/744
Processed batch 144/744
Processed batch 145/744
Processed batch 146/744
Processed batch 147/744
Processed batch 148/744
Processed batch 149/744
Processed batch 150/744
Processed batch 151/744
Processed batch 152/744
Processed batch 153/744
Processed batch 154/744
Processed batch 155/744
Processed batch 156/744
Processed batch 157/744
Processed batch 158/744
Processed batch 159/744
Processed batch 160/744
Processed batch 161/744
Processed batch 162/744
Processed batch 163/744
Processed batch 164/744
Processed batch 165/744
Processed batch 166/744
Processed batch 167/744
Processed batch 168/744
Processed batch 169/744
Processed batch 170/744
Processed batch 171/744
Processed batch 172/744
Processed batch 173/744
Processed batch 174/744
Processed batch 175/744
Processed batch 176/744
Processed batch 177/744
Processed batch 178/744
Processed batch 179/744
Processed batch 180/744
Processed batch 181/744
Processed batch 182/744
Processed batch 183/744
Processed batch 184/744
Processed batch 185/744
Processed batch 186/744
Processed batch 187/744
Processed batch 188/744
Processed batch 189/744
Processed batch 190/744
Processed batch 191/744
Processed batch 192/744
Processed batch 193/744
Processed batch 194/744
Processed batch 195/744
Processed batch 196/744
Processed batch 197/744
Processed batch 198/744
Processed batch 199/744
Processed batch 200/744
Processed batch 201/744
Processed batch 202/744
Processed batch 203/744
Processed batch 204/744
Processed batch 205/744
Processed batch 206/744
Processed batch 207/744
Processed batch 208/744
Processed batch 209/744
Processed batch 210/744
Processed batch 211/744
Processed batch 212/744
Processed batch 213/744
Processed batch 214/744
Processed batch 215/744
Processed batch 216/744
Processed batch 217/744
Processed batch 218/744
Processed batch 219/744
Processed batch 220/744
Processed batch 221/744
Processed batch 222/744
Processed batch 223/744
Processed batch 224/744
Processed batch 225/744
Processed batch 226/744
Processed batch 227/744
Processed batch 228/744
Processed batch 229/744
Processed batch 230/744
Processed batch 231/744
Processed batch 232/744
Processed batch 233/744
Processed batch 234/744
Processed batch 235/744
Processed batch 236/744
Processed batch 237/744
Processed batch 238/744
Processed batch 239/744
Processed batch 240/744
Processed batch 241/744
Processed batch 242/744
Processed batch 243/744
Processed batch 244/744
Processed batch 245/744
Processed batch 246/744
Processed batch 247/744
Processed batch 248/744
Processed batch 249/744
Processed batch 250/744
Processed batch 251/744
Processed batch 252/744
Processed batch 253/744
Processed batch 254/744
Processed batch 255/744
Processed batch 256/744
Processed batch 257/744
Processed batch 258/744
Processed batch 259/744
Processed batch 260/744
Processed batch 261/744
Processed batch 262/744
Processed batch 263/744
Processed batch 264/744
Processed batch 265/744
Processed batch 266/744
Processed batch 267/744
Processed batch 268/744
Processed batch 269/744
Processed batch 270/744
Processed batch 271/744
Processed batch 272/744
Processed batch 273/744
Processed batch 274/744
Processed batch 275/744
Processed batch 276/744
Processed batch 277/744
Processed batch 278/744
Processed batch 279/744
Processed batch 280/744
Processed batch 281/744
Processed batch 282/744
Processed batch 283/744
Processed batch 284/744
Processed batch 285/744
Processed batch 286/744
Processed batch 287/744
Processed batch 288/744
Processed batch 289/744
Processed batch 290/744
Processed batch 291/744
Processed batch 292/744
Processed batch 293/744
Processed batch 294/744
Processed batch 295/744
Processed batch 296/744
Processed batch 297/744
Processed batch 298/744
Processed batch 299/744
Processed batch 300/744
Processed batch 301/744
Processed batch 302/744
Processed batch 303/744
Processed batch 304/744
Processed batch 305/744
Processed batch 306/744
Processed batch 307/744
Processed batch 308/744
Processed batch 309/744
Processed batch 310/744
Processed batch 311/744
Processed batch 312/744
Processed batch 313/744
Processed batch 314/744
Processed batch 315/744
Processed batch 316/744
Processed batch 317/744
Processed batch 318/744
Processed batch 319/744
Processed batch 320/744
Processed batch 321/744
Processed batch 322/744
Processed batch 323/744
Processed batch 324/744
Processed batch 325/744
Processed batch 326/744
Processed batch 327/744
Processed batch 328/744
Processed batch 329/744
Processed batch 330/744
Processed batch 331/744
Processed batch 332/744
Processed batch 333/744
Processed batch 334/744
Processed batch 335/744
Processed batch 336/744
Processed batch 337/744
Processed batch 338/744
Processed batch 339/744
Processed batch 340/744
Processed batch 341/744
Processed batch 342/744
Processed batch 343/744
Processed batch 344/744
Processed batch 345/744
Processed batch 346/744
Processed batch 347/744
Processed batch 348/744
Processed batch 349/744
Processed batch 350/744
Processed batch 351/744
Processed batch 352/744
Processed batch 353/744
Processed batch 354/744
Processed batch 355/744
Processed batch 356/744
Processed batch 357/744
Processed batch 358/744
Processed batch 359/744
Processed batch 360/744
Processed batch 361/744
Processed batch 362/744
Processed batch 363/744
Processed batch 364/744
Processed batch 365/744
Processed batch 366/744
Processed batch 367/744
Processed batch 368/744
Processed batch 369/744
Processed batch 370/744
Processed batch 371/744
Processed batch 372/744
Processed batch 373/744
Processed batch 374/744
Processed batch 375/744
Processed batch 376/744
Processed batch 377/744
Processed batch 378/744
Processed batch 379/744
Processed batch 380/744
Processed batch 381/744
Processed batch 382/744
Processed batch 383/744
Processed batch 384/744
Processed batch 385/744
Processed batch 386/744
Processed batch 387/744
Processed batch 388/744
Processed batch 389/744
Processed batch 390/744
Processed batch 391/744
Processed batch 392/744
Processed batch 393/744
Processed batch 394/744
Processed batch 395/744
Processed batch 396/744
Processed batch 397/744
Processed batch 398/744
Processed batch 399/744
Processed batch 400/744
Processed batch 401/744
Processed batch 402/744
Processed batch 403/744
Processed batch 404/744
Processed batch 405/744
Processed batch 406/744
Processed batch 407/744
Processed batch 408/744
Processed batch 409/744
Processed batch 410/744
Processed batch 411/744
Processed batch 412/744
Processed batch 413/744
Processed batch 414/744
Processed batch 415/744
Processed batch 416/744
Processed batch 417/744
Processed batch 418/744
Processed batch 419/744
Processed batch 420/744
Processed batch 421/744
Processed batch 422/744
Processed batch 423/744
Processed batch 424/744
Processed batch 425/744
Processed batch 426/744
Processed batch 427/744
Processed batch 428/744
Processed batch 429/744
Processed batch 430/744
Processed batch 431/744
Processed batch 432/744
Processed batch 433/744
Processed batch 434/744
Processed batch 435/744
Processed batch 436/744
Processed batch 437/744
Processed batch 438/744
Processed batch 439/744
Processed batch 440/744
Processed batch 441/744
Processed batch 442/744
Processed batch 443/744
Processed batch 444/744
Processed batch 445/744
Processed batch 446/744
Processed batch 447/744
Processed batch 448/744
Processed batch 449/744
Processed batch 450/744
Processed batch 451/744
Processed batch 452/744
Processed batch 453/744
Processed batch 454/744
Processed batch 455/744
Processed batch 456/744
Processed batch 457/744
Processed batch 458/744
Processed batch 459/744
Processed batch 460/744
Processed batch 461/744
Processed batch 462/744
Processed batch 463/744
Processed batch 464/744
Processed batch 465/744
Processed batch 466/744
Processed batch 467/744
Processed batch 468/744
Processed batch 469/744
Processed batch 470/744
Processed batch 471/744
Processed batch 472/744
Processed batch 473/744
Processed batch 474/744
Processed batch 475/744
Processed batch 476/744
Processed batch 477/744
Processed batch 478/744
Processed batch 479/744
Processed batch 480/744
Processed batch 481/744
Processed batch 482/744
Processed batch 483/744
Processed batch 484/744
Processed batch 485/744
Processed batch 486/744
Processed batch 487/744
Processed batch 488/744
Processed batch 489/744
Processed batch 490/744
Processed batch 491/744
Processed batch 492/744
Processed batch 493/744
Processed batch 494/744
Processed batch 495/744
Processed batch 496/744
Processed batch 497/744
Processed batch 498/744
Processed batch 499/744
Processed batch 500/744
Processed batch 501/744
Processed batch 502/744
Processed batch 503/744
Processed batch 504/744
Processed batch 505/744
Processed batch 506/744
Processed batch 507/744
Processed batch 508/744
Processed batch 509/744
Processed batch 510/744
Processed batch 511/744
Processed batch 512/744
Processed batch 513/744
Processed batch 514/744
Processed batch 515/744
Processed batch 516/744
Processed batch 517/744
Processed batch 518/744
Processed batch 519/744
Processed batch 520/744
Processed batch 521/744
Processed batch 522/744
Processed batch 523/744
Processed batch 524/744
Processed batch 525/744
Processed batch 526/744
Processed batch 527/744
Processed batch 528/744
Processed batch 529/744
Processed batch 530/744
Processed batch 531/744
Processed batch 532/744
Processed batch 533/744
Processed batch 534/744
Processed batch 535/744
Processed batch 536/744
Processed batch 537/744
Processed batch 538/744
Processed batch 539/744
Processed batch 540/744
Processed batch 541/744
Processed batch 542/744
Processed batch 543/744
Processed batch 544/744
Processed batch 545/744
Processed batch 546/744
Processed batch 547/744
Processed batch 548/744
Processed batch 549/744
Processed batch 550/744
Processed batch 551/744
Processed batch 552/744
Processed batch 553/744
Processed batch 554/744
Processed batch 555/744
Processed batch 556/744
Processed batch 557/744
Processed batch 558/744
Processed batch 559/744
Processed batch 560/744
Processed batch 561/744
Processed batch 562/744
Processed batch 563/744
Processed batch 564/744
Processed batch 565/744
Processed batch 566/744
Processed batch 567/744
Processed batch 568/744
Processed batch 569/744
Processed batch 570/744
Processed batch 571/744
Processed batch 572/744
Processed batch 573/744
Processed batch 574/744
Processed batch 575/744
Processed batch 576/744
Processed batch 577/744
Processed batch 578/744
Processed batch 579/744
Processed batch 580/744
Processed batch 581/744
Processed batch 582/744
Processed batch 583/744
Processed batch 584/744
Processed batch 585/744
Processed batch 586/744
Processed batch 587/744
Processed batch 588/744
Processed batch 589/744
Processed batch 590/744
Processed batch 591/744
Processed batch 592/744
Processed batch 593/744
Processed batch 594/744
Processed batch 595/744
Processed batch 596/744
Processed batch 597/744
Processed batch 598/744
Processed batch 599/744
Processed batch 600/744
Processed batch 601/744
Processed batch 602/744
Processed batch 603/744
Processed batch 604/744
Processed batch 605/744
Processed batch 606/744
Processed batch 607/744
Processed batch 608/744
Processed batch 609/744
Processed batch 610/744
Processed batch 611/744
Processed batch 612/744
Processed batch 613/744
Processed batch 614/744
Processed batch 615/744
Processed batch 616/744
Processed batch 617/744
Processed batch 618/744
Processed batch 619/744
Processed batch 620/744
Processed batch 621/744
Processed batch 622/744
Processed batch 623/744
Processed batch 624/744
Processed batch 625/744
Processed batch 626/744
Processed batch 627/744
Processed batch 628/744
Processed batch 629/744
Processed batch 630/744
Processed batch 631/744
Processed batch 632/744
Processed batch 633/744
Processed batch 634/744
Processed batch 635/744
Processed batch 636/744
Processed batch 637/744
Processed batch 638/744
Processed batch 639/744
Processed batch 640/744
Processed batch 641/744
Processed batch 642/744
Processed batch 643/744
Processed batch 644/744
Processed batch 645/744
Processed batch 646/744
Processed batch 647/744
Processed batch 648/744
Processed batch 649/744
Processed batch 650/744
Processed batch 651/744
Processed batch 652/744
Processed batch 653/744
Processed batch 654/744
Processed batch 655/744
Processed batch 656/744
Processed batch 657/744
Processed batch 658/744
Processed batch 659/744
Processed batch 660/744
Processed batch 661/744
Processed batch 662/744
Processed batch 663/744
Processed batch 664/744
Processed batch 665/744
Processed batch 666/744
Processed batch 667/744
Processed batch 668/744
Processed batch 669/744
Processed batch 670/744
Processed batch 671/744
Processed batch 672/744
Processed batch 673/744
Processed batch 674/744
Processed batch 675/744
Processed batch 676/744
Processed batch 677/744
Processed batch 678/744
Processed batch 679/744
Processed batch 680/744
Processed batch 681/744
Processed batch 682/744
Processed batch 683/744
Processed batch 684/744
Processed batch 685/744
Processed batch 686/744
Processed batch 687/744
Processed batch 688/744
Processed batch 689/744
Processed batch 690/744
Processed batch 691/744
Processed batch 692/744
Processed batch 693/744
Processed batch 694/744
Processed batch 695/744
Processed batch 696/744
Processed batch 697/744
Processed batch 698/744
Processed batch 699/744
Processed batch 700/744
Processed batch 701/744
Processed batch 702/744
Processed batch 703/744
Processed batch 704/744
Processed batch 705/744
Processed batch 706/744
Processed batch 707/744
Processed batch 708/744
Processed batch 709/744
Processed batch 710/744
Processed batch 711/744
Processed batch 712/744
Processed batch 713/744
Processed batch 714/744
Processed batch 715/744
Processed batch 716/744
Processed batch 717/744
Processed batch 718/744
Processed batch 719/744
Processed batch 720/744
Processed batch 721/744
Processed batch 722/744
Processed batch 723/744
Processed batch 724/744
Processed batch 725/744
Processed batch 726/744
Processed batch 727/744
Processed batch 728/744
Processed batch 729/744
Processed batch 730/744
Processed batch 731/744
Processed batch 732/744
Processed batch 733/744
Processed batch 734/744
Processed batch 735/744
Processed batch 736/744
Processed batch 737/744
Processed batch 738/744
Processed batch 739/744
Processed batch 740/744
Processed batch 741/744
Processed batch 742/744
Processed batch 743/744
Processed batch 744/744

C:\Users\naomi\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:2072: UserWarning: Only (<class 'numpy.float64'>, <class 'numpy.float32'>, <class 'numpy.float16'>) 'dtype' should be used. <class 'float'> 'dtype' will be converted to np.float64.
  warnings.warn(

In [17]:
relations_df.head()

,Word_Pair,Word1,Word1_Category,Word2,Word2_Category,Count,Word1_occurrence,Word2_occurrence,Count_weighted
0,"(aandeel, energierekening)",aandeel,Overige,energierekening,Duurzaamheid,3,67,19,0.002357
1,"(aandeel, energie)",aandeel,Overige,energie,Duurzaamheid,51,67,373,0.002041
2,"(aandeel, klimaatakkoord)",aandeel,Overige,klimaatakkoord,Duurzaamheid,2,67,157,0.000190
3,"(aandeel, energieakkoord)",aandeel,Overige,energieakkoord,Duurzaamheid,1,67,23,0.000649
4,"(aandeel, energieverbruik)",aandeel,Overige,energieverbruik,Duurzaamheid,2,67,50,0.000597

In [18]:
relations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Word_Pair         772 non-null    object
 1   Word1             772 non-null    object
 2   Word1_Category    772 non-null    object
 3   Word2             772 non-null    object
 4   Word2_Category    772 non-null    object
 5   Count             772 non-null    int64
 6   Word1_occurrence  772 non-null    int64
 7   Word2_occurrence  772 non-null    int64
 8   Count_weighted    772 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 54.4+ KB

In [19]:
df_data.head()

,Phrase,Page,Priority,word_pairs
0,"[integraal, nationaal, energie, klimaatplan, o...",6,1.0,"[(integraal, nationaal), (integraal, energie),..."
1,"[inek, bevat, hoofdlijnen, klimaat, energiebel...",6,1.0,"[(inek, bevat), (inek, hoofdlijnen), (inek, kl..."
2,"[inhoud, belangrijk, deel, bepaald, klimaatakk...",6,1.0,"[(inhoud, belangrijk), (inhoud, deel), (inhoud..."
3,"[akkoord, bevat, pakket, maatregelen, actieve,...",6,1.0,"[(akkoord, bevat), (akkoord, pakket), (akkoord..."
4,"[aanvulling, nieuwe, nationale, maatregelen, k...",6,1.0,"[(aanvulling, nieuwe), (aanvulling, nationale)..."

In [20]:
relations_df.shape

(772, 9)

In [21]:
relations_df.columns

Index(['Word_Pair', 'Word1', 'Word1_Category', 'Word2', 'Word2_Category',
       'Count', 'Word1_occurrence', 'Word2_occurrence', 'Count_weighted'],
      dtype='object')

In [22]:
# Change column names
# relations_df.columns = ['Word Pair', 'Source', 'Target', 'Count', 'Source_Occurrence', 'Target_Occurrence', 'Edge_Weight']
relations_df.columns = ['Word Pair', 'Source','Source_Category', 'Target','Target_Category', 'Count', 'Source_Occurrence', 'Target_Occurrence', 'Edge_Weight']

In [23]:
relations_df.head(50)

,Word Pair,Source,Source_Category,Target,Target_Category,Count,Source_Occurrence,Target_Occurrence,Edge_Weight
0,"(aandeel, energierekening)",aandeel,Overige,energierekening,Duurzaamheid,3,67,19,0.002357
1,"(aandeel, energie)",aandeel,Overige,energie,Duurzaamheid,51,67,373,0.002041
2,"(aandeel, klimaatakkoord)",aandeel,Overige,klimaatakkoord,Duurzaamheid,2,67,157,0.000190
3,"(aandeel, energieakkoord)",aandeel,Overige,energieakkoord,Duurzaamheid,1,67,23,0.000649
4,"(aandeel, energieverbruik)",aandeel,Overige,energieverbruik,Duurzaamheid,2,67,50,0.000597
5,"(aandeel, biobrandstoffen)",aandeel,Overige,biobrandstoffen,Duurzaamheid,2,67,26,0.001148
6,"(aantal, klimaatakkoord)",aantal,Overige,klimaatakkoord,Duurzaamheid,2,57,157,0.000223
7,"(aantal, energieverbruik)",aantal,Overige,energieverbruik,Duurzaamheid,1,57,50,0.000351
8,"(aardgas, energierekening)",aardgas,Overige,energierekening,Duurzaamheid,1,72,19,0.000731
9,"(aardgas, energie)",aardgas,Overige,energie,Duurzaamheid,3,72,373,0.000112
10,"(activiteiten, energieverbruik)",activiteiten,Overige,energieverbruik,Duurzaamheid,1,36,50,0.000556
11,"(activiteiten, duurzaam)",activiteiten,Overige,duurzaam,Duurzaamheid,1,36,16,0.001736
12,"(activiteiten, energieinnovatie)",activiteiten,Overige,energieinnovatie,Duurzaamheid,3,36,12,0.006944
13,"(activiteiten, energie)",activiteiten,Overige,energie,Duurzaamheid,4,36,373,0.000298
14,"(afbakening, duurzaam)",afbakening,Overige,duurzaam,Duurzaamheid,1,1,16,0.062500
15,"(afhankelijkheid, energie)",afhankelijkheid,Overige,energie,Duurzaamheid,3,7,373,0.001149
16,"(afhankelijkheid, biobrandstoffen)",afhankelijkheid,Overige,biobrandstoffen,Duurzaamheid,1,7,26,0.005495
17,"(april, energie)",april,Overige,energie,Duurzaamheid,1,6,373,0.000447
18,"(arbeid, energie)",arbeid,Overige,energie,Duurzaamheid,1,15,373,0.000179
19,"(arbeidsjaren, energie)",arbeidsjaren,Overige,energie,Duurzaamheid,1,7,373,0.000383
20,"(bandbreedte, klimaatakkoord)",bandbreedte,Overige,klimaatakkoord,Duurzaamheid,2,18,157,0.000708
21,"(beginnen, klimaatakkoord)",beginnen,Overige,klimaatakkoord,Duurzaamheid,1,2,157,0.003185
22,"(beleid, energieverbruik)",beleid,Overige,energieverbruik,Duurzaamheid,1,125,50,0.000160
23,"(beleid, biobrandstoffen)",beleid,Overige,biobrandstoffen,Duurzaamheid,1,125,26,0.000308
24,"(beleid, energie)",beleid,Overige,energie,Duurzaamheid,9,125,373,0.000193
25,"(beleid, energiebelasting)",beleid,Overige,energiebelasting,Duurzaamheid,1,125,22,0.000364
26,"(beleid, energierekening)",beleid,Overige,energierekening,Duurzaamheid,1,125,19,0.000421
27,"(beleid, energiearmoede)",beleid,Overige,energiearmoede,Duurzaamheid,3,125,15,0.001600
28,"(beleidsinstrumenten, klimaatakkoord)",beleidsinstrumenten,Overige,klimaatakkoord,Duurzaamheid,3,9,157,0.002123
29,"(beleidsvarianten, energieakkoord)",beleidsvarianten,Overige,energieakkoord,Duurzaamheid,1,4,23,0.010870
30,"(belgie, energieforum)",belgie,Overige,energieforum,Duurzaamheid,1,20,8,0.006250
31,"(besparing, energierekening)",besparing,Overige,energierekening,Duurzaamheid,1,16,19,0.003289
32,"(besparing, energieverbruik)",besparing,Overige,energieverbruik,Duurzaamheid,3,16,50,0.003750
33,"(betalingsachterstand, energierekening)",betalingsachterstand,Overige,energierekening,Duurzaamheid,5,7,19,0.037594
34,"(bevat, energieverbruik)",bevat,Overige,energieverbruik,Duurzaamheid,1,23,50,0.000870
35,"(bevat, energiebeleid)",bevat,Overige,energiebeleid,Duurzaamheid,1,23,21,0.002070
36,"(bevat, energieprestatie)",bevat,Overige,energieprestatie,Duurzaamheid,1,23,15,0.002899
37,"(bevat, energieakkoord)",bevat,Overige,energieakkoord,Duurzaamheid,1,23,23,0.001890
38,"(bijdrage, energie)",bijdrage,Overige,energie,Duurzaamheid,17,54,373,0.000844
39,"(bijdrage, klimaatakkoord)",bijdrage,Overige,klimaatakkoord,Duurzaamheid,1,54,157,0.000118
40,"(bijdrage, energieverbruik)",bijdrage,Overige,energieverbruik,Duurzaamheid,7,54,50,0.002593
41,"(biobrandstoffen, velden)",biobrandstoffen,Duurzaamheid,velden,Overige,1,26,16,0.002404
42,"(biobrandstoffen, voorkeur)",biobrandstoffen,Duurzaamheid,voorkeur,Overige,1,26,6,0.006410
43,"(biobrandstoffen, veilig)",biobrandstoffen,Duurzaamheid,veilig,Overige,1,26,6,0.006410
44,"(biobrandstoffen, groene)",biobrandstoffen,Duurzaamheid,groene,Duurzaamheid,1,26,22,0.001748
45,"(biobrandstoffen, markt)",biobrandstoffen,Duurzaamheid,markt,Overige,1,26,56,0.000687
46,"(biobrandstoffen, maatregelen)",biobrandstoffen,Duurzaamheid,maatregelen,Overige,1,26,139,0.000277
47,"(biobrandstoffen, waterstof)",biobrandstoffen,Duurzaamheid,waterstof,Mobiliteit,1,26,34,0.001131
48,"(biobrandstoffen, bijdrage)",biobrandstoffen,Duurzaamheid,bijdrage,Overige,1,26,54,0.000712
49,"(biobrandstoffen, landen)",biobrandstoffen,Duurzaamheid,landen,Overige,1,26,63,0.000611

In [24]:
# Sort DataFrame by 'Weight' column in descending order
sorted_df = (relations_df.copy()).sort_values(by='Edge_Weight', ascending=False)

sorted_df.head(50)

,Word Pair,Source,Source_Category,Target,Target_Category,Count,Source_Occurrence,Target_Occurrence,Edge_Weight
730,"(variabiliteit, elektriciteitsopwekkingde)",variabiliteit,Duurzaamheid,elektriciteitsopwekkingde,Overige,1,1,1,1.000000
658,"(pblnotitie, klimaattransitie)",pblnotitie,Overige,klimaattransitie,Duurzaamheid,1,1,2,0.500000
710,"(statistieken, variabiliteit)",statistieken,Overige,variabiliteit,Duurzaamheid,1,2,1,0.500000
360,"(energiequote, betaalrisico)",energiequote,Duurzaamheid,betaalrisico,Overige,14,11,6,0.212121
578,"(klimaattransitie, update)",klimaattransitie,Duurzaamheid,update,Overige,1,2,3,0.166667
649,"(onzeker, variabiliteit)",onzeker,Overige,variabiliteit,Duurzaamheid,1,9,1,0.111111
579,"(klimaattransitie, april)",klimaattransitie,Duurzaamheid,april,Overige,1,2,6,0.083333
69,"(conventioneel, duurzaam)",conventioneel,Overige,duurzaam,Duurzaamheid,1,1,16,0.062500
14,"(afbakening, duurzaam)",afbakening,Overige,duurzaam,Duurzaamheid,1,1,16,0.062500
87,"(duurzaam, achtergrondrapportages)",duurzaam,Duurzaamheid,achtergrondrapportages,Overige,1,16,1,0.062500
731,"(variabiliteit, bandbreedte)",variabiliteit,Duurzaamheid,bandbreedte,Overige,1,1,18,0.055556
548,"(klimaatakkoord, kavel)",klimaatakkoord,Duurzaamheid,kavel,Overige,8,157,1,0.050955
690,"(restwarmte, geleverde)",restwarmte,Duurzaamheid,geleverde,Overige,2,7,6,0.047619
362,"(energiequote, hoge)",energiequote,Duurzaamheid,hoge,Overige,12,11,25,0.043636
329,"(energieinnovatie, dei)",energieinnovatie,Duurzaamheid,dei,Overige,1,12,2,0.041667
593,"(landgebruik, variabiliteit)",landgebruik,Mobiliteit,variabiliteit,Duurzaamheid,1,25,1,0.040000
33,"(betalingsachterstand, energierekening)",betalingsachterstand,Overige,energierekening,Duurzaamheid,5,7,19,0.037594
732,"(variabiliteit, reductie)",variabiliteit,Duurzaamheid,reductie,Overige,2,1,58,0.034483
610,"(methodiek, energieprestatie)",methodiek,Overige,energieprestatie,Duurzaamheid,2,4,15,0.033333
359,"(energiequote, inkomen)",energiequote,Duurzaamheid,inkomen,Overige,6,11,17,0.032086
83,"(duurzaam, dril)",duurzaam,Duurzaamheid,dril,Water,1,16,2,0.031250
318,"(energieefficientie, beleidsinstrumenten)",energieefficientie,Duurzaamheid,beleidsinstrumenten,Overige,3,11,9,0.030303
768,"(zonnestroom, megawatt)",zonnestroom,Duurzaamheid,megawatt,Overige,2,6,12,0.027778
341,"(energieonderzoek, scope)",energieonderzoek,Duurzaamheid,scope,Overige,1,7,6,0.023810
438,"(groene, waterstof)",groene,Duurzaamheid,waterstof,Mobiliteit,17,22,34,0.022727
288,"(energiebelasting, eb)",energiebelasting,Duurzaamheid,eb,Water,1,22,2,0.022727
167,"(energie, kavel)",energie,Duurzaamheid,kavel,Overige,8,373,1,0.021448
334,"(energieinnovatie, clean)",energieinnovatie,Duurzaamheid,clean,Overige,1,12,4,0.020833
356,"(energiequote, huishoudens)",energiequote,Duurzaamheid,huishoudens,Overige,15,11,69,0.019763
347,"(energieprestatie, gebouwen)",energieprestatie,Duurzaamheid,gebouwen,Overige,11,15,38,0.019298
364,"(energiequote, alleen)",energiequote,Duurzaamheid,alleen,Overige,6,11,29,0.018809
693,"(scoort, groene)",scoort,Overige,groene,Duurzaamheid,3,8,22,0.017045
354,"(energiequote, indicator)",energiequote,Duurzaamheid,indicator,Overige,2,11,11,0.016529
551,"(klimaatakkoord, hollandse)",klimaatakkoord,Duurzaamheid,hollandse,Overige,5,157,2,0.015924
78,"(definities, duurzaam)",definities,Overige,duurzaam,Duurzaamheid,1,4,16,0.015625
345,"(energieprestatie, eisen)",energieprestatie,Duurzaamheid,eisen,Overige,3,15,13,0.015385
457,"(indicatieve, energieefficientie)",indicatieve,Overige,energieefficientie,Duurzaamheid,5,30,11,0.015152
311,"(energieefficientie, stellen)",energieefficientie,Duurzaamheid,stellen,Overige,2,11,12,0.015152
292,"(energiebelasting, ode)",energiebelasting,Duurzaamheid,ode,Overige,5,22,16,0.014205
665,"(percentage, energierekening)",percentage,Overige,energierekening,Duurzaamheid,4,15,19,0.014035
351,"(energieprestatie, calculatie)",energieprestatie,Duurzaamheid,calculatie,Overige,1,15,5,0.013333
374,"(energierekening, scoort)",energierekening,Duurzaamheid,scoort,Overige,2,19,8,0.013158
373,"(energierekening, stijgt)",energierekening,Duurzaamheid,stijgt,Overige,3,19,12,0.013158
611,"(methodiek, energierekening)",methodiek,Overige,energierekening,Duurzaamheid,1,4,19,0.013158
88,"(duurzaam, verwezen)",duurzaam,Duurzaamheid,verwezen,Overige,1,16,5,0.012500
486,"(kamerbrief, klimaattransitie)",kamerbrief,Overige,klimaattransitie,Duurzaamheid,1,40,2,0.012500
63,"(circulaire, klimaattransitie)",circulaire,Overige,klimaattransitie,Duurzaamheid,1,41,2,0.012195
302,"(energiebeleid, inkomens)",energiebeleid,Duurzaamheid,inkomens,Overige,1,21,4,0.011905
467,"(inkomenseffecten, energiebeleid)",inkomenseffecten,Overige,energiebeleid,Duurzaamheid,1,4,21,0.011905
764,"(ziet, groene)",ziet,Overige,groene,Duurzaamheid,1,4,22,0.011364

In [25]:
# to csv
relations_df.to_csv('inek.csv', index=False)

In [26]:
# run GephiVisualization_nieuw notebook

%run Visualization_Final_Winnovation.ipynb

Community Leaders:
{3: 'beleid', 2: 'energie', 7: 'klimaatakkoord', 8: 'nr', 5: 'nederland', 1: 'elektriciteit', 0: 'co', 6: 'gas', 4: 'reductie'}
Theme/cluster: co: Red
Theme/cluster: elektriciteit: Yellow
Theme/cluster: energie: Cyan
Theme/cluster: beleid: Green
Theme/cluster: reductie: Pink
Theme/cluster: nederland: Blue
Theme/cluster: gas: Purple
Theme/cluster: klimaatakkoord: Light Pink
Theme/cluster: nr: Red
Cluster: co (Color: Red):
  Node: co, Node_Weight: 23.66
  Node: emissies, Node_Weight: 11.08
  Node: activiteiten, Node_Weight: 3.76
  Node: energy, Node_Weight: 2.47
  Node: kansen, Node_Weight: 2.26
  Node: overige, Node_Weight: 2.26
  Node: innovation, Node_Weight: 2.04
  Node: informatie, Node_Weight: 1.40
  Node: energieinnovatie, Node_Weight: 1.18
  Node: restwarmte, Node_Weight: 0.65
  Node: geleverde, Node_Weight: 0.54
  Node: clean, Node_Weight: 0.32
  Node: dei, Node_Weight: 0.11

Cluster: elektriciteit (Color: Yellow):
  Node: elektriciteit, Node_Weight: 14.95
  Node: maatregelen, Node_Weight: 14.84
  Node: per, Node_Weight: 13.12
  Node: groei, Node_Weight: 8.17
  Node: vraag, Node_Weight: 6.88
  Node: tenopzichte, Node_Weight: 6.67
  Node: inzet, Node_Weight: 6.67
  Node: markt, Node_Weight: 5.91
  Node: economische, Node_Weight: 5.81
  Node: extra, Node_Weight: 4.95
  Node: waterstof, Node_Weight: 3.55
  Node: effecten, Node_Weight: 3.44
  Node: prijs, Node_Weight: 3.44
  Node: biobrandstoffen, Node_Weight: 2.69
  Node: stimuleren, Node_Weight: 2.69
  Node: groene, Node_Weight: 2.26
  Node: energiebeleid, Node_Weight: 2.15
  Node: iea, Node_Weight: 1.94
  Node: derde, Node_Weight: 1.72
  Node: mmip, Node_Weight: 1.72
  Node: velden, Node_Weight: 1.61
  Node: lasten, Node_Weight: 1.40
  Node: cpb, Node_Weight: 1.29
  Node: hoofdlijnen, Node_Weight: 1.08
  Node: beleidsinstrumenten, Node_Weight: 0.86
  Node: technieken, Node_Weight: 0.75
  Node: afhankelijkheid, Node_Weight: 0.65
  Node: factor, Node_Weight: 0.65
  Node: voorkeur, Node_Weight: 0.54
  Node: deals, Node_Weight: 0.43
  Node: ziet, Node_Weight: 0.32
  Node: inkomens, Node_Weight: 0.32
  Node: inkomenseffecten, Node_Weight: 0.32

Cluster: energie (Color: Cyan):
  Node: energie, Node_Weight: 40.00
  Node: kosten, Node_Weight: 5.48
  Node: circulaire, Node_Weight: 4.30
  Node: kamerbrief, Node_Weight: 4.19
  Node: flexibiliteit, Node_Weight: 3.55
  Node: staat, Node_Weight: 2.90
  Node: hoogcalorisch, Node_Weight: 2.58
  Node: ruimtelijke, Node_Weight: 2.26
  Node: topsectoren, Node_Weight: 2.15
  Node: groningenveld, Node_Weight: 1.94
  Node: aardolie, Node_Weight: 1.83
  Node: conventionele, Node_Weight: 1.72
  Node: innovatiebeleid, Node_Weight: 1.72
  Node: twh, Node_Weight: 1.72
  Node: arbeid, Node_Weight: 1.51
  Node: opties, Node_Weight: 1.51
  Node: liquiditeit, Node_Weight: 1.40
  Node: verbindingen, Node_Weight: 1.40
  Node: waarvan, Node_Weight: 1.40
  Node: netten, Node_Weight: 1.29
  Node: mln, Node_Weight: 1.29
  Node: uitbreiding, Node_Weight: 1.29
  Node: onze, Node_Weight: 1.18
  Node: koninkrijk, Node_Weight: 1.18
  Node: verenigd, Node_Weight: 1.18
  Node: bcm, Node_Weight: 1.08
  Node: concurrentie, Node_Weight: 1.08
  Node: interconnectie, Node_Weight: 1.08
  Node: acerceer, Node_Weight: 1.08
  Node: htl, Node_Weight: 1.08
  Node: hoogspanningsnet, Node_Weight: 0.97
  Node: interconnectiviteit, Node_Weight: 0.97
  Node: emissierechten, Node_Weight: 0.97
  Node: processen, Node_Weight: 0.97
  Node: verklaring, Node_Weight: 0.97
  Node: dienstensector, Node_Weight: 0.86
  Node: uitvoer, Node_Weight: 0.86
  Node: regelingen, Node_Weight: 0.86
  Node: mmips, Node_Weight: 0.75
  Node: arbeidsjaren, Node_Weight: 0.65
  Node: isde, Node_Weight: 0.65
  Node: mijlpaal, Node_Weight: 0.65
  Node: churn, Node_Weight: 0.65
  Node: bedragen, Node_Weight: 0.65
  Node: aspecten, Node_Weight: 0.65
  Node: smart, Node_Weight: 0.65
  Node: april, Node_Weight: 0.54
  Node: noodzaak, Node_Weight: 0.54
  Node: hubs, Node_Weight: 0.54
  Node: brandstofprijzen, Node_Weight: 0.43
  Node: aardgasprijs, Node_Weight: 0.32
  Node: vertrouwen, Node_Weight: 0.32
  Node: wkk, Node_Weight: 0.32
  Node: ziektelast, Node_Weight: 0.32
  Node: octrooien, Node_Weight: 0.32
  Node: merken, Node_Weight: 0.32
  Node: netverliezen, Node_Weight: 0.32
  Node: octrooiaanvragen, Node_Weight: 0.32
  Node: tcp, Node_Weight: 0.32
  Node: ddee, Node_Weight: 0.22
  Node: update, Node_Weight: 0.22
  Node: uitvoerwaarde, Node_Weight: 0.22
  Node: klimaattransitie, Node_Weight: 0.11
  Node: cost, Node_Weight: 0.11
  Node: aftrek, Node_Weight: 0.11
  Node: inkomsten, Node_Weight: 0.11
  Node: staatssteun, Node_Weight: 0.11

Cluster: beleid (Color: Green):
  Node: beleid, Node_Weight: 13.33
  Node: huishoudens, Node_Weight: 7.31
  Node: aandeel, Node_Weight: 7.10
  Node: emissie, Node_Weight: 4.52
  Node: kennis, Node_Weight: 4.30
  Node: programma, Node_Weight: 3.66
  Node: we, Node_Weight: 3.55
  Node: alleen, Node_Weight: 3.01
  Node: regeling, Node_Weight: 2.90
  Node: kleinverbruikers, Node_Weight: 2.80
  Node: hoge, Node_Weight: 2.58
  Node: kleine, Node_Weight: 2.47
  Node: energierekening, Node_Weight: 1.94
  Node: indicatoren, Node_Weight: 1.94
  Node: inkomen, Node_Weight: 1.72
  Node: besparing, Node_Weight: 1.61
  Node: energiearmoede, Node_Weight: 1.51
  Node: woning, Node_Weight: 1.51
  Node: percentage, Node_Weight: 1.51
  Node: daalt, Node_Weight: 1.40
  Node: stijgt, Node_Weight: 1.18
  Node: tevredenheid, Node_Weight: 1.08
  Node: indicator, Node_Weight: 1.08
  Node: energiequote, Node_Weight: 1.08
  Node: scoort, Node_Weight: 0.75
  Node: betalingsachterstand, Node_Weight: 0.65
  Node: betaalrisico, Node_Weight: 0.54
  Node: schulden, Node_Weight: 0.43

Cluster: reductie (Color: Pink):
  Node: reductie, Node_Weight: 6.13
  Node: landgebruik, Node_Weight: 2.58
  Node: bandbreedte, Node_Weight: 1.83
  Node: onzeker, Node_Weight: 0.86
  Node: statistieken, Node_Weight: 0.11

Cluster: nederland (Color: Blue):
  Node: nederland, Node_Weight: 34.62
  Node: hernieuwbare, Node_Weight: 20.00
  Node: tussen, Node_Weight: 12.69
  Node: nationale, Node_Weight: 12.15
  Node: verwachting, Node_Weight: 11.51
  Node: periode, Node_Weight: 10.75
  Node: figuur, Node_Weight: 10.65
  Node: aardgas, Node_Weight: 7.63
  Node: kev, Node_Weight: 7.20
  Node: totale, Node_Weight: 6.34
  Node: ontwikkelingen, Node_Weight: 5.81
  Node: bijdrage, Node_Weight: 5.70
  Node: petajoule, Node_Weight: 5.70
  Node: verbruik, Node_Weight: 5.59
  Node: verduurzaming, Node_Weight: 5.38
  Node: energieverbruik, Node_Weight: 5.27
  Node: biomassa, Node_Weight: 5.16
  Node: voorgenomen, Node_Weight: 5.05
  Node: sde, Node_Weight: 4.19
  Node: procent, Node_Weight: 3.76
  Node: heffing, Node_Weight: 3.33
  Node: indicatieve, Node_Weight: 3.12
  Node: burgers, Node_Weight: 2.80
  Node: projecties, Node_Weight: 2.69
  Node: waarde, Node_Weight: 2.37
  Node: energiebelasting, Node_Weight: 2.26
  Node: cumulatieve, Node_Weight: 2.26
  Node: verduurzamen, Node_Weight: 1.94
  Node: toegevoegde, Node_Weight: 1.83
  Node: ode, Node_Weight: 1.61
  Node: megawatt, Node_Weight: 1.18
  Node: energieefficientie, Node_Weight: 1.08
  Node: aardolieproducten, Node_Weight: 0.75
  Node: daalde, Node_Weight: 0.65
  Node: bevolking, Node_Weight: 0.65
  Node: zonnestroom, Node_Weight: 0.54
  Node: stadsverwarming, Node_Weight: 0.43
  Node: eb, Node_Weight: 0.11

Cluster: gas (Color: Purple):
  Node: gas, Node_Weight: 10.00
  Node: gebouwde, Node_Weight: 9.25
  Node: landen, Node_Weight: 6.67
  Node: inek, Node_Weight: 3.12
  Node: duitsland, Node_Weight: 3.01
  Node: cbs, Node_Weight: 2.90
  Node: warmte, Node_Weight: 2.90
  Node: laagcalorisch, Node_Weight: 2.58
  Node: belgie, Node_Weight: 2.04
  Node: duurzaam, Node_Weight: 1.61
  Node: green, Node_Weight: 1.51
  Node: energiegerelateerde, Node_Weight: 1.08
  Node: et, Node_Weight: 0.97
  Node: deal, Node_Weight: 0.86
  Node: energieforum, Node_Weight: 0.75
  Node: veilig, Node_Weight: 0.54
  Node: onderscheid, Node_Weight: 0.54
  Node: definities, Node_Weight: 0.32
  Node: dril, Node_Weight: 0.11

Cluster: klimaatakkoord (Color: Light Pink):
  Node: klimaatakkoord, Node_Weight: 16.77
  Node: investeringen, Node_Weight: 12.47
  Node: megaton, Node_Weight: 7.53
  Node: equivalenten, Node_Weight: 6.99
  Node: euro, Node_Weight: 5.91
  Node: mton, Node_Weight: 5.59
  Node: innovatie, Node_Weight: 4.52
  Node: miljard, Node_Weight: 3.76
  Node: onderzoek, Node_Weight: 3.66
  Node: elektriciteitsproductie, Node_Weight: 3.23
  Node: dalen, Node_Weight: 2.80
  Node: res, Node_Weight: 2.58
  Node: middelen, Node_Weight: 2.58
  Node: tevens, Node_Weight: 1.83
  Node: ontwerp, Node_Weight: 1.83
  Node: pakket, Node_Weight: 1.83
  Node: missiegedreven, Node_Weight: 1.61
  Node: diversificatie, Node_Weight: 1.40
  Node: vormgeving, Node_Weight: 1.40
  Node: participatie, Node_Weight: 1.40
  Node: arbeidsmarkt, Node_Weight: 1.40
  Node: concept, Node_Weight: 1.18
  Node: missies, Node_Weight: 1.08
  Node: nietets, Node_Weight: 1.08
  Node: wijkgerichte, Node_Weight: 1.08
  Node: bouwen, Node_Weight: 0.97
  Node: gerelateerd, Node_Weight: 0.97
  Node: tm, Node_Weight: 0.75
  Node: gedragsonzekerheid, Node_Weight: 0.65
  Node: energieonderzoek, Node_Weight: 0.65
  Node: werk, Node_Weight: 0.65
  Node: areaal, Node_Weight: 0.65
  Node: scp, Node_Weight: 0.65
  Node: scope, Node_Weight: 0.54
  Node: voorstel, Node_Weight: 0.54
  Node: kton, Node_Weight: 0.43
  Node: herstel, Node_Weight: 0.43
  Node: eerder, Node_Weight: 0.32
  Node: kust, Node_Weight: 0.32
  Node: broeikasgas, Node_Weight: 0.22
  Node: kavels, Node_Weight: 0.22
  Node: gepresenteerd, Node_Weight: 0.22
  Node: vormgevingsonzekerheid, Node_Weight: 0.22
  Node: beginnen, Node_Weight: 0.11
  Node: hollandse, Node_Weight: 0.11

Cluster: nr (Color: Red):
  Node: nr, Node_Weight: 6.77
  Node: kamerstuk, Node_Weight: 6.24
  Node: aantal, Node_Weight: 6.02
  Node: komt, Node_Weight: 5.91
  Node: gebouwen, Node_Weight: 3.98
  Node: woningen, Node_Weight: 3.33
  Node: werkgelegenheid, Node_Weight: 3.33
  Node: regeerakkoord, Node_Weight: 2.90
  Node: juni, Node_Weight: 2.58
  Node: energieakkoord, Node_Weight: 2.37
  Node: bevat, Node_Weight: 2.37
  Node: klimaatwet, Node_Weight: 2.04
  Node: energieprestatie, Node_Weight: 1.51
  Node: eisen, Node_Weight: 1.29
  Node: gw, Node_Weight: 1.29
  Node: juli, Node_Weight: 1.29
  Node: stellen, Node_Weight: 1.18
  Node: kostenoptimale, Node_Weight: 0.54
  Node: verwezen, Node_Weight: 0.43
  Node: calculatie, Node_Weight: 0.43
  Node: beleidsvarianten, Node_Weight: 0.32
  Node: methodiek, Node_Weight: 0.32

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
inek.html